use serde::{Deserialize, Serialize};

use super::identifiers::ObjectId;
use super::phase::Phase;
use super::player::PlayerId;
use super::zones::Zone;

/// A structured game log entry with typed segments and metadata.
/// Generated by the engine post-hoc from `GameEvent`s with resolved card/player names.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GameLogEntry {
    pub seq: u32,
    pub turn: u32,
    pub phase: Phase,
    pub category: LogCategory,
    pub segments: Vec<LogSegment>,
}

/// A typed segment of a log entry, enabling rich UI rendering.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", content = "value")]
pub enum LogSegment {
    Text(String),
    CardName { name: String, object_id: ObjectId },
    PlayerName { name: String, player_id: PlayerId },
    Number(i32),
    Mana(String),
    Zone(Zone),
    Keyword(String),
}

/// Categories for log entries, used for verbosity filtering in the frontend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LogCategory {
    Game,
    Turn,
    Stack,
    Combat,
    Zone,
    Life,
    Mana,
    State,
    Token,
    Trigger,
    Special,
    Destroy,
    Debug,
}
