//! Duration combinators for Oracle text parsing.
//!
//! **Single authority for the phrase→`Duration` grammar** (oracle-parser
//! SKILL §7). Parses: "until end of turn", "until end of combat", "until the
//! end of your/their next turn", "until your/their next turn", "until your
//! next end step", "until ~/this creature leaves the battlefield", "until you
//! exile another card with ~/this ability", "for the rest of the game", "for
//! as long as [condition]", "this turn", "this/that combat".
//!
//! Positional wrappers (`strip_trailing_duration` / `strip_leading_duration`
//! in `oracle_effect/lower.rs`, the clause shell, and the combat-grant
//! parsers in `oracle_effect/subject.rs`) decide WHERE a duration clause
//! sits; the phrase→variant mapping lives only here. Adding a new duration
//! phrase means editing only this file.

use nom::branch::alt;
use nom::bytes::complete::{tag, take_until};
use nom::character::complete::multispace0;
use nom::combinator::{eof, map, opt, rest, value, verify};
use nom::sequence::{preceded, terminated};
use nom::Parser;

use super::condition::{parse_inner_condition, parse_recipient_has_counters};
use super::error::{oracle_err, OracleError, OracleResult};
use super::primitives::scan_contains;
use crate::types::ability::{Duration, ObjectScope, PlayerScope, StaticCondition};
use crate::types::phase::Phase;

/// Parse a duration phrase from Oracle text.
///
/// Nested by prefix dispatch: the shared "until " and "for " heads are
/// factored once, then the body sub-combinators dispatch on the remainder.
///
/// Note: the "for as long as [condition]" branch is clause-final — it
/// consumes the rest of its input (see `parse_for_as_long_as_condition`).
pub fn parse_duration(input: &str) -> OracleResult<'_, Duration> {
    alt((
        preceded(tag("until "), parse_until_body),
        preceded(tag("for "), parse_for_body),
        parse_current_phase_duration,
    ))
    .parse(input)
}

/// Alternatives after the shared "until " prefix.
fn parse_until_body(input: &str) -> OracleResult<'_, Duration> {
    alt((
        value(Duration::UntilEndOfTurn, tag("end of turn")),
        // CR 511.2: effects that last "until end of combat" expire at the end
        // of the combat phase.
        value(Duration::UntilEndOfCombat, tag("end of combat")),
        parse_until_end_of_next_turn,
        parse_until_next_turn,
        // CR 513.1 + CR 611.2a: Rocco, Street Chef and the floating
        // play-permission class — "until your next end step".
        value(
            Duration::UntilNextStepOf {
                step: Phase::End,
                player: PlayerScope::Controller,
            },
            tag("your next end step"),
        ),
        // Host-lifetime expiry: "until ~ leaves the battlefield" /
        // "until this creature leaves the battlefield".
        value(
            Duration::UntilHostLeavesPlay,
            (
                alt((tag("~"), tag("this creature"))),
                tag(" leaves the battlefield"),
            ),
        ),
        // CR 607.2a + CR 611.2a: source-linked impulse grants such as
        // Furious Rise last until the same source exiles another card.
        value(
            Duration::UntilSourceExilesAnotherCard,
            parse_until_source_exiles_another_card_body,
        ),
    ))
    .parse(input)
}

pub(crate) fn parse_until_source_exiles_another_card_body(input: &str) -> OracleResult<'_, ()> {
    let (input, _) = tag("you exile another card with ").parse(input)?;
    let (input, _) = alt((
        tag::<_, _, OracleError<'_>>("~"),
        tag("this ability"),
        tag("this enchantment"),
        tag("this artifact"),
        tag("this creature"),
        tag("this permanent"),
    ))
    .parse(input)?;
    Ok((input, ()))
}

/// Alternatives after the shared "for " prefix.
fn parse_for_body(input: &str) -> OracleResult<'_, Duration> {
    alt((
        // CR 611.2a: "A continuous effect generated by the resolution of a
        // spell or ability lasts as long as stated by the spell or ability
        // creating it ... If no duration is stated, it lasts until the end of
        // the game." A continuous restriction worded "... for the rest of the
        // game" (Screaming Nemesis: "can't gain life for the rest of the
        // game") therefore has no expiry — modeled as `Duration::Permanent`.
        // CR 119.7 governs the restriction's semantics for the "can't gain
        // life" case specifically.
        value(Duration::Permanent, tag("the rest of the game")),
        // CR 611.2b: "for as long as" durations embed a condition that is
        // continuously checked — effect expires when the condition becomes
        // false.
        preceded(tag("as long as "), parse_for_as_long_as_condition),
    ))
    .parse(input)
}

/// Current-phase demonstratives: "this turn", "this combat", "that combat".
fn parse_current_phase_duration(input: &str) -> OracleResult<'_, Duration> {
    alt((
        preceded(
            tag("this "),
            alt((
                value(Duration::UntilEndOfTurn, tag("turn")),
                // CR 511.2: "this combat" scopes a grant or restriction to the
                // current combat — end-of-combat expiry.
                value(Duration::UntilEndOfCombat, tag("combat")),
            )),
        ),
        // CR 511.2: demonstrative "that combat" (grants referencing an
        // additional or identified combat phase) shares end-of-combat expiry.
        value(Duration::UntilEndOfCombat, tag("that combat")),
    ))
    .parse(input)
}

fn parse_next_turn_pronoun(input: &str) -> OracleResult<'_, PlayerScope> {
    // CR 109.5 + CR 608.2c: in this shared duration parser, "your" and
    // third-person "their" are both resolved by the caller's controller/grantee
    // binding; runtime pruning currently arms Controller-scoped durations.
    alt((
        value(PlayerScope::Controller, tag("your")),
        value(PlayerScope::Controller, tag("their")),
    ))
    .parse(input)
}

fn parse_until_end_of_next_turn(input: &str) -> OracleResult<'_, Duration> {
    // CR 514.2: "until the end of [your/their] next turn" persists through the
    // whole next turn (cleanup), distinct from "until [your/their] next turn"
    // (beginning of next turn). CR 108.3: third-person "their" appears in
    // grants whose grantee is not the ability's controller (Suspend
    // Aggression, Expedited Inheritance); the grantee binding resolves the
    // Controller scope at prune time.
    let (rest, _) = tag("the end of ").parse(input)?;
    let (rest, player) = parse_next_turn_pronoun(rest)?;
    let (rest, _) = tag(" next turn").parse(rest)?;
    Ok((rest, Duration::UntilEndOfNextTurnOf { player }))
}

fn parse_until_next_turn(input: &str) -> OracleResult<'_, Duration> {
    let (rest, player) = parse_next_turn_pronoun(input)?;
    let (rest, _) = tag(" next turn").parse(rest)?;
    Ok((rest, Duration::UntilNextTurnOf { player }))
}

/// CR 611.2b: map the condition text after "for as long as " to a `Duration`.
///
/// Mapping (ported verbatim from the legacy `strip_trailing_duration` table):
/// - compound "[a] and [b]" → `ForAsLongAs(And[..])`
/// - "[subject] remains tapped" → `ForAsLongAs(SourceIsTapped)` for source
///   subjects, `ForAsLongAs(IsTapped { scope: Target })` for demonstrative
///   subjects (see `parse_remains_tapped`)
/// - "you control [subject]" → `UntilHostLeavesPlay`
/// - "[subject] remains on the battlefield" → `UntilHostLeavesPlay`
/// - "[subject] has [N] [type] counter(s) on it" → `ForAsLongAs(HasCounters)`
/// - any whole-clause condition `parse_inner_condition` recognizes →
///   `ForAsLongAs(condition)`
/// - otherwise → `ForAsLongAs(Unrecognized)` (coverage parity with the legacy
///   strip table; the swallow detectors flag the unrecognized text)
///
/// Clause-final: every arm consumes the remainder of its input — the phrase
/// sits at the trailing edge of an effect clause in Oracle text.
pub fn parse_for_as_long_as_condition(input: &str) -> OracleResult<'_, Duration> {
    alt((
        parse_compound_for_as_long_as,
        // "[subject] remains tapped" — the grammatical subject selects the
        // tracked object's scope. Demonstrative subjects ("that creature") bind
        // the duration to the copy/control TARGET; source subjects ("~", "this
        // creature", bare card names) bind to the source. See
        // `parse_remains_tapped`.
        parse_remains_tapped,
        // "you control [subject]" → host-control lifetime, modeled with the
        // existing UntilHostLeavesPlay variant.
        value(
            Duration::UntilHostLeavesPlay,
            preceded(tag("you control "), rest),
        ),
        // "[subject] remains on the battlefield" → UntilHostLeavesPlay.
        value(
            Duration::UntilHostLeavesPlay,
            verify(rest, |tail: &str| {
                scan_contains(tail, "remains on the battlefield")
            }),
        ),
        // CR 122.1 + CR 611.2b: "[subject] has [N] [type] counter[s] on it" —
        // delegate to the recipient-aware counter-condition combinator so the
        // bound pronoun "it" in "for as long as it has a counter" binds to the
        // affected object (the controlled/granted creature), evaluated by the
        // layer system. A source subject ("~"/"this creature") stays
        // `HasCounters`. The typed/bare/quantity grammar lives in one authority.
        map(
            terminated(parse_recipient_has_counters, (multispace0, eof)),
            |condition| Duration::ForAsLongAs { condition },
        ),
        // Any whole-clause condition the shared condition grammar recognizes.
        map(
            terminated(parse_inner_condition, (multispace0, eof)),
            |condition| Duration::ForAsLongAs { condition },
        ),
        // Fallback: unrecognized condition text.
        map(rest, |text: &str| Duration::ForAsLongAs {
            condition: StaticCondition::Unrecognized {
                text: text.trim().trim_end_matches('.').to_string(),
            },
        }),
    ))
    .parse(input)
}

/// CR 110.5b + CR 611.2b: subject-aware "[subject] remains tapped" duration.
///
/// The grammatical subject of "remains tapped" selects which object's tap state
/// the `ForAsLongAs` duration tracks:
///
/// - **Demonstrative subjects** ("that creature/permanent/artifact") → the
///   copy/control TARGET. Emits `IsTapped { scope: Target }` so the resolver
///   (`become_copy.rs`) binds the duration to the resolved target object (Zygon
///   Infiltrator: "as long as THAT creature remains tapped" tracks the copied
///   creature, not Zygon). This tier is tried FIRST.
///
/// The anaphoric pronoun "it" is deliberately NOT in the demonstrative set: its
/// referent is clause-context-dependent ("you control ~ and it remains tapped"
/// → "it" is the source; "tap another target permanent. Its abilities can't be
/// activated for as long as it remains tapped" → "it" is the target). The
/// duration combinator has no clause subject to disambiguate, so "it" falls to
/// the source fallback (the pre-existing behavior), preserving every "it
/// remains tapped" card's current parse. The only cluster card needing the
/// target binding (Zygon) uses the unambiguous "that creature".
/// - **Source subjects** ("~", "this creature", a `SELF_REF_TYPE_PHRASES`
///   self-reference, or a bare card name like "The Blackstaff of Waterdeep") →
///   the source. Emits `SourceIsTapped`. The explicit self-reference `alt()`
///   plus the retained `scan_contains` word-boundary fallback covers every
///   source phrasing, including proper names beginning with "The".
///
/// Demonstrative dispatch MUST precede the source fallback so a proper-name card
/// is never misread as a target subject and "that creature" is never swallowed
/// by the source `scan_contains` scan. The closed demonstrative `alt()`
/// deliberately excludes any "the " arm — a leading "The" belongs to a card name
/// (source), not a demonstrative. Compound cards (Hivis, Rubinia) are split by
/// `parse_compound_for_as_long_as` before this combinator runs, so each side
/// re-enters here and lands on the source fallback.
fn parse_remains_tapped(input: &str) -> OracleResult<'_, Duration> {
    // Each tier is clause-final: a trailing `rest` consumes any remainder after
    // "[subject] remains tapped" so the arm behaves like the legacy `verify(rest,
    // ..)` arm (the phrase sits at the trailing edge of the effect clause).
    //
    // Tier 1: demonstrative subject → target-relative tap state.
    let demonstrative = value(
        Duration::ForAsLongAs {
            condition: StaticCondition::IsTapped {
                scope: ObjectScope::Target,
            },
        },
        (
            alt((
                tag("that creature"),
                tag("that permanent"),
                tag("that artifact"),
            )),
            tag(" remains tapped"),
            rest,
        ),
    );

    // Tier 2a: explicit source self-reference → source-relative tap state.
    let source_self_ref = value(
        Duration::ForAsLongAs {
            condition: StaticCondition::SourceIsTapped,
        },
        (parse_self_reference_subject, tag(" remains tapped"), rest),
    );

    // Tier 2b: any other source phrasing (proper card names like "The Blackstaff
    // of Waterdeep", compound-clause remnants) → source. Word-boundary scan, not
    // a dispatch primitive, and only reached after demonstrative dispatch fails.
    let source_fallback = value(
        Duration::ForAsLongAs {
            condition: StaticCondition::SourceIsTapped,
        },
        verify(rest, |tail: &str| scan_contains(tail, "remains tapped")),
    );

    alt((demonstrative, source_self_ref, source_fallback)).parse(input)
}

/// Source self-reference subject combinator: "~" or any `SELF_REF_TYPE_PHRASES`
/// phrase ("this creature", "this permanent", …). Iterates the shared
/// self-reference constant — the single authority for source self-references —
/// so no card-specific phrasing leaks in. (`SELF_REF_TYPE_PHRASES` is a runtime
/// slice, so the closed set is folded by iteration rather than a fixed `alt()`
/// tuple; each candidate is still matched with the nom `tag()` combinator.)
fn parse_self_reference_subject(input: &str) -> OracleResult<'_, ()> {
    for phrase in std::iter::once(&"~").chain(crate::parser::oracle_util::SELF_REF_TYPE_PHRASES) {
        if let Ok((rest, _)) = tag::<_, _, OracleError<'_>>(*phrase).parse(input) {
            return Ok((rest, ()));
        }
    }
    // No self-reference subject matched — surface a recoverable nom error so the
    // outer `alt()` falls through to the `scan_contains` source fallback.
    Err(oracle_err(input))
}

/// Compound "for as long as [a] and [b]" → `ForAsLongAs(And[..])`.
fn parse_compound_for_as_long_as(input: &str) -> OracleResult<'_, Duration> {
    let (right, left) = terminated(take_until(" and "), tag(" and ")).parse(input)?;
    let (_, left_dur) = parse_for_as_long_as_condition(left.trim())?;
    let (_, right_dur) = parse_for_as_long_as_condition(right.trim())?;
    Ok((
        "",
        Duration::ForAsLongAs {
            condition: StaticCondition::And {
                conditions: vec![
                    duration_to_condition(left_dur),
                    duration_to_condition(right_dur),
                ],
            },
        },
    ))
}

/// Convert a `Duration` back into a `StaticCondition` for compound "and"
/// clauses. `UntilHostLeavesPlay` maps to `IsPresent { filter: None }`
/// (source must remain on the battlefield).
fn duration_to_condition(dur: Duration) -> StaticCondition {
    match dur {
        Duration::ForAsLongAs { condition } => condition,
        Duration::UntilHostLeavesPlay => StaticCondition::IsPresent { filter: None },
        _ => StaticCondition::None,
    }
}

/// Parse an optional trailing duration: returns `Some(Duration)` if present,
/// `None` if no duration phrase follows. Does NOT consume leading whitespace.
pub fn parse_optional_duration(input: &str) -> OracleResult<'_, Option<Duration>> {
    match parse_duration(input) {
        Ok((rest, d)) => Ok((rest, Some(d))),
        Err(_) => Ok((input, None)),
    }
}

/// CR 608.2h + CR 608.2i: the cast/activation-time value-snapshot suffix.
/// CR 608.2h fixes a computed value once when the effect is applied; CR 608.2i
/// is the past-tense ("you controlled") look-back exception sharing this
/// grammar. The suffix is a pure timing marker — it does not change the object
/// filter — so callers strip it before the empty-remainder filter check and let
/// the resolver perform the snapshot.
pub fn parse_cast_snapshot_suffix(input: &str) -> OracleResult<'_, ()> {
    preceded(
        opt(tag(" ")),
        value(
            (),
            alt((
                tag("as you cast this spell"),
                tag("as you cast it"),
                tag("as you activate this ability"),
            )),
        ),
    )
    .parse(input)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::ability::StaticCondition;

    #[test]
    fn test_parse_duration_end_of_turn() {
        let (rest, d) = parse_duration("until end of turn.").unwrap();
        assert_eq!(d, Duration::UntilEndOfTurn);
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_duration_end_of_combat() {
        let (rest, d) = parse_duration("until end of combat").unwrap();
        assert_eq!(d, Duration::UntilEndOfCombat);
        assert_eq!(rest, "");
    }

    #[test]
    fn test_parse_duration_next_turn() {
        let (rest, d) = parse_duration("until your next turn and").unwrap();
        assert_eq!(
            d,
            Duration::UntilNextTurnOf {
                player: PlayerScope::Controller,
            }
        );
        assert_eq!(rest, " and");
    }

    #[test]
    fn test_parse_duration_until_end_of_next_turn() {
        let (rest, d) = parse_duration("until the end of their next turn.").unwrap();
        assert_eq!(
            d,
            Duration::UntilEndOfNextTurnOf {
                player: PlayerScope::Controller,
            }
        );
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_duration_their_next_turn() {
        let (rest, d) = parse_duration("until their next turn.").unwrap();
        assert_eq!(
            d,
            Duration::UntilNextTurnOf {
                player: PlayerScope::Controller,
            }
        );
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_duration_this_turn() {
        let (rest, d) = parse_duration("this turn.").unwrap();
        assert_eq!(d, Duration::UntilEndOfTurn);
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_duration_for_as_long_as() {
        let (rest, d) = parse_duration("for as long as ~ is tapped").unwrap();
        assert_eq!(rest, "");
        match d {
            Duration::ForAsLongAs { condition } => {
                assert!(matches!(condition, StaticCondition::SourceIsTapped));
            }
            _ => panic!("expected ForAsLongAs"),
        }
    }

    #[test]
    fn test_parse_duration_for_the_rest_of_the_game() {
        let (rest, d) = parse_duration("for the rest of the game.").unwrap();
        assert_eq!(d, Duration::Permanent);
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_duration_until_host_leaves_battlefield() {
        for text in [
            "until ~ leaves the battlefield",
            "until this creature leaves the battlefield",
        ] {
            let (rest, d) = parse_duration(text).unwrap();
            assert_eq!(d, Duration::UntilHostLeavesPlay, "failed for {text:?}");
            assert_eq!(rest, "");
        }
    }

    #[test]
    fn test_parse_duration_until_source_exiles_another_card() {
        for text in [
            "until you exile another card with ~",
            "until you exile another card with this ability",
            "until you exile another card with this enchantment",
        ] {
            let (rest, d) = parse_duration(text).unwrap();
            assert_eq!(
                d,
                Duration::UntilSourceExilesAnotherCard,
                "failed for {text:?}"
            );
            assert_eq!(rest, "");
        }
    }

    #[test]
    fn test_parse_duration_this_and_that_combat() {
        for text in ["this combat", "that combat"] {
            let (rest, d) = parse_duration(text).unwrap();
            assert_eq!(d, Duration::UntilEndOfCombat, "failed for {text:?}");
            assert_eq!(rest, "");
        }
    }

    #[test]
    fn test_parse_duration_this_combat_if_able_leaves_remainder() {
        let (rest, d) = parse_duration("this combat if able").unwrap();
        assert_eq!(d, Duration::UntilEndOfCombat);
        assert_eq!(rest, " if able");
    }

    #[test]
    fn test_parse_duration_until_your_next_end_step() {
        let (rest, d) = parse_duration("until your next end step, ").unwrap();
        assert_eq!(
            d,
            Duration::UntilNextStepOf {
                step: Phase::End,
                player: PlayerScope::Controller,
            }
        );
        assert_eq!(rest, ", ");
    }

    #[test]
    fn test_for_as_long_as_you_control_maps_to_until_host_leaves() {
        let (rest, d) = parse_duration("for as long as you control ~").unwrap();
        assert_eq!(d, Duration::UntilHostLeavesPlay);
        assert_eq!(rest, "");
    }

    #[test]
    fn test_for_as_long_as_remains_on_battlefield_maps_to_until_host_leaves() {
        let (_, d) = parse_duration("for as long as ~ remains on the battlefield").unwrap();
        assert_eq!(d, Duration::UntilHostLeavesPlay);
    }

    #[test]
    fn test_for_as_long_as_compound_control_and_tapped() {
        let (rest, d) =
            parse_duration("for as long as you control ~ and it remains tapped").unwrap();
        assert_eq!(rest, "");
        match d {
            Duration::ForAsLongAs {
                condition: StaticCondition::And { conditions },
            } => {
                assert_eq!(conditions.len(), 2);
                assert!(matches!(
                    conditions[0],
                    StaticCondition::IsPresent { filter: None }
                ));
                assert!(matches!(conditions[1], StaticCondition::SourceIsTapped));
            }
            other => panic!("expected ForAsLongAs(And[..]), got {other:?}"),
        }
    }

    #[test]
    fn test_for_as_long_as_unrecognized_fallback() {
        let (rest, d) = parse_duration("for as long as the moon is full").unwrap();
        assert_eq!(rest, "");
        match d {
            Duration::ForAsLongAs {
                condition: StaticCondition::Unrecognized { text },
            } => assert_eq!(text, "the moon is full"),
            other => panic!("expected ForAsLongAs(Unrecognized), got {other:?}"),
        }
    }

    #[test]
    fn test_parse_optional_duration_present() {
        let (rest, d) = parse_optional_duration("until end of turn.").unwrap();
        assert_eq!(d, Some(Duration::UntilEndOfTurn));
        assert_eq!(rest, ".");
    }

    #[test]
    fn test_parse_optional_duration_absent() {
        let (rest, d) = parse_optional_duration("and draws a card").unwrap();
        assert_eq!(d, None);
        assert_eq!(rest, "and draws a card");
    }

    #[test]
    fn test_parse_duration_failure() {
        assert!(parse_duration("permanently").is_err());
    }

    #[test]
    fn test_cast_snapshot_suffix_cast_this_spell_leading_space() {
        assert_eq!(
            parse_cast_snapshot_suffix(" as you cast this spell"),
            Ok(("", ()))
        );
    }

    #[test]
    fn test_cast_snapshot_suffix_cast_it_leading_space() {
        assert_eq!(parse_cast_snapshot_suffix(" as you cast it"), Ok(("", ())));
    }

    #[test]
    fn test_cast_snapshot_suffix_activate_ability_leading_space() {
        assert_eq!(
            parse_cast_snapshot_suffix(" as you activate this ability"),
            Ok(("", ()))
        );
    }

    #[test]
    fn test_cast_snapshot_suffix_no_leading_space() {
        assert_eq!(
            parse_cast_snapshot_suffix("as you cast this spell"),
            Ok(("", ()))
        );
    }

    #[test]
    fn test_cast_snapshot_suffix_rejects_duration() {
        assert!(parse_cast_snapshot_suffix(" until end of turn").is_err());
    }

    #[test]
    fn test_cast_snapshot_suffix_rejects_empty() {
        assert!(parse_cast_snapshot_suffix("").is_err());
    }

    #[test]
    fn test_cast_snapshot_suffix_trailing_period() {
        assert_eq!(
            parse_cast_snapshot_suffix(" as you cast this spell."),
            Ok((".", ()))
        );
    }

    // ---- "remains tapped" subject-aware duration (CR 110.5b + CR 611.2b) ----

    /// Demonstrative subject ("that creature") → target-relative tap state. This
    /// is the Zygon Infiltrator copy-duration class: the duration must track the
    /// copied creature (the target), not the source.
    #[test]
    fn test_remains_tapped_demonstrative_binds_target() {
        for subject in ["that creature", "that permanent", "that artifact"] {
            let text = format!("for as long as {subject} remains tapped");
            let (rest, d) = parse_duration(&text).unwrap();
            assert_eq!(rest, "", "failed for {subject:?}");
            assert_eq!(
                d,
                Duration::ForAsLongAs {
                    condition: StaticCondition::IsTapped {
                        scope: ObjectScope::Target,
                    },
                },
                "demonstrative subject {subject:?} must bind the target",
            );
        }
    }

    /// Source self-reference ("this creature"/"~") → source-relative tap state
    /// (`SourceIsTapped`) — the 41-card source-subject majority of the class.
    #[test]
    fn test_remains_tapped_self_reference_binds_source() {
        for subject in ["~", "this creature", "this artifact", "this permanent"] {
            let text = format!("for as long as {subject} remains tapped");
            let (rest, d) = parse_duration(&text).unwrap();
            assert_eq!(rest, "", "failed for {subject:?}");
            assert_eq!(
                d,
                Duration::ForAsLongAs {
                    condition: StaticCondition::SourceIsTapped,
                },
                "self-reference subject {subject:?} must bind the source",
            );
        }
    }

    /// Proper-name regression: a card name beginning with "The" is a SOURCE
    /// subject and must NOT be misread as a demonstrative target despite the
    /// leading "The" (Animate Walking Statue → The Blackstaff of Waterdeep; The
    /// Pandorica). Guards the closed demonstrative `alt()` from a "the " leak.
    #[test]
    fn test_remains_tapped_proper_name_binds_source() {
        for subject in ["The Blackstaff of Waterdeep", "The Pandorica"] {
            let text = format!("for as long as {subject} remains tapped");
            let (rest, d) = parse_duration(&text).unwrap();
            assert_eq!(rest, "", "failed for {subject:?}");
            assert_eq!(
                d,
                Duration::ForAsLongAs {
                    condition: StaticCondition::SourceIsTapped,
                },
                "proper-name subject {subject:?} must stay source-bound",
            );
        }
    }

    /// Compound regression (Hivis / Rubinia): "you control X and X remains
    /// tapped" splits on " and " and each side re-enters the combinator; the
    /// "X remains tapped" side hits the source fallback → `SourceIsTapped`. The
    /// new demonstrative tier must not perturb the compound path.
    #[test]
    fn test_remains_tapped_compound_card_name_binds_source() {
        for name in ["rubinia soulsinger", "hivis"] {
            let text = format!("for as long as you control {name} and {name} remains tapped");
            let (rest, d) = parse_duration(&text).unwrap();
            assert_eq!(rest, "", "failed for {name:?}");
            match d {
                Duration::ForAsLongAs {
                    condition: StaticCondition::And { conditions },
                } => {
                    assert_eq!(conditions.len(), 2, "failed for {name:?}");
                    assert!(
                        matches!(conditions[0], StaticCondition::IsPresent { filter: None }),
                        "control side for {name:?}",
                    );
                    assert!(
                        matches!(conditions[1], StaticCondition::SourceIsTapped),
                        "tapped side for {name:?} must be source-bound",
                    );
                }
                other => panic!("expected ForAsLongAs(And[..]) for {name:?}, got {other:?}"),
            }
        }
    }

    /// Anaphoric "it" stays source-bound (the pre-existing behavior): "it" is
    /// excluded from the demonstrative set because its referent is clause-context
    /// dependent. This pins the decision so a future edit cannot silently move
    /// "it" into the target-binding tier and regress the compound-control class.
    #[test]
    fn test_remains_tapped_it_stays_source() {
        let (rest, d) = parse_duration("for as long as it remains tapped").unwrap();
        assert_eq!(rest, "");
        assert_eq!(
            d,
            Duration::ForAsLongAs {
                condition: StaticCondition::SourceIsTapped,
            },
        );
    }
}
