// Local render smoke test — no Discord credentials needed.
//   bun scripts/card-bot/smoke.ts "Lightning Bolt"
//   bun scripts/card-bot/smoke.ts "Snapcaster Mage" path/to/coverage-data.json
//
// Tokens and both faces of a double-faced card need Scryfall data. Point the bot
// at a local scryfall-data.json (generated by gen-scryfall-images.sh) instead of
// R2 with CARD_BOT_SCRYFALL_FILE, then:
//   CARD_BOT_SCRYFALL_FILE=scryfall.json bun scripts/card-bot/smoke.ts "Pilot"
//   CARD_BOT_SCRYFALL_FILE=scryfall.json bun scripts/card-bot/smoke.ts "Peter Parker"
//
// Loads the local coverage export, renders the embed(s) for a card, and prints
// each description with live ANSI so the terminal shows Discord's colors.

import type { CoverageEntry } from "./coverageData";
import type { Embed } from "./render";
import { renderCardEmbed, renderFaceFallback, renderNotFound, renderTokenEmbed } from "./render";
import { lookupScryfall, lookupToken } from "./scryfall";

const META = { commit_short: "abc1234", mtgjson_date: "2026-04-18" };

const name = process.argv[2] ?? "Lightning Bolt";
const file = process.argv[3] ?? "client/public/coverage-data.json";

const data = JSON.parse(await Bun.file(file).text()) as { cards: CoverageEntry[] };
const coverage = new Map<string, CoverageEntry>();
for (const c of data.cards) {
  if (c.card_name) coverage.set(c.card_name.toLowerCase(), c);
}

async function buildEmbeds(): Promise<Embed[]> {
  const entry = coverage.get(name.toLowerCase());
  if (!entry) {
    // Not a playable card — try tokens before reporting not-found.
    const token = await lookupToken(name);
    return [token ? renderTokenEmbed(token, "release", META) : renderNotFound(name, "release")];
  }

  const scry = await lookupScryfall(entry.card_name);
  if (scry && scry.faceNames.length > 1) {
    const embeds: Embed[] = [];
    for (let i = 0; i < scry.faceNames.length; i++) {
      const faceEntry = coverage.get(scry.faceNames[i]);
      const faceImage = scry.faceImages[i] ?? null;
      embeds.push(
        faceEntry
          ? renderCardEmbed(faceEntry, scry, "release", META, { faceImage, descriptionBudget: 2600 })
          : renderFaceFallback(scry.faceNames[i], faceImage, "release", META),
      );
    }
    return embeds;
  }

  return [renderCardEmbed(entry, scry, "release", META)];
}

const embeds = await buildEmbeds();
console.log(`=== ${embeds.length} embed(s) for "${name}" ===\n`);
for (const [i, embed] of embeds.entries()) {
  console.log(`--- embed ${i + 1}: ${embed.author?.name ?? ""}  (thumbnail: ${embed.thumbnail?.url ?? "none"}) ---`);
  console.log(embed.description ?? "(no description)");
  console.log("");
}
